# Generated by Django 3.2.22 on 2023-10-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231022_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_box_size',
            new_name='is_filled',
        ),
    ]
